import { Injectable } from "@nestjs/common";
import PDFDocument from "pdfkit";
import { join } from "path";

/**
 * Shared PDF rendering (receipts + the four reports). Uses the bundled
 * Noto Sans font — NOT Helvetica, which has no ₹ glyph and silently prints
 * "Rs." instead (documented bug from the frontend mock phase).
 */
const FONT_DIR = join(__dirname, "..", "..", "assets", "fonts");
export const FONT_REGULAR = join(FONT_DIR, "NotoSans-Regular.ttf");
export const FONT_BOLD = join(FONT_DIR, "NotoSans-Bold.ttf");

const NAVY = "#1b2a4a";
const GOLD = "#b08d57";

export interface PdfOrgHeader {
  hostelName: string;
  addressLine?: string;
  city?: string;
  state?: string;
  pincode?: string;
  phone?: string;
}

export interface PdfTableColumn {
  label: string;
  width: number; // in pt, page content width is 540
  align?: "left" | "right";
}

/** ₹ with Indian digit grouping, from integer paisa. */
export function pdfMoney(paisa: number): string {
  const rupees = paisa / 100;
  return `₹${rupees.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
}

@Injectable()
export class PdfService {
  /** Builds a complete PDF in memory and resolves with its bytes. */
  private render(build: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: "A4", margin: 36, bufferPages: true });
      const chunks: Buffer[] = [];
      doc.on("data", (c: Buffer) => chunks.push(c));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);
      doc.registerFont("body", FONT_REGULAR);
      doc.registerFont("bold", FONT_BOLD);
      build(doc);
      doc.end();
    });
  }

  private header(doc: PDFKit.PDFDocument, org: PdfOrgHeader, title: string): void {
    doc.rect(0, 0, doc.page.width, 74).fill(NAVY);
    doc.fill("#ffffff").font("bold").fontSize(15);
    doc.text(org.hostelName || "Saahvik Hostel", 36, 20);
    doc.font("body").fontSize(8);
    const address = [org.addressLine, org.city, org.state, org.pincode]
      .filter(Boolean)
      .join(", ");
    if (address) doc.text(address, 36, 42);
    if (org.phone) doc.text(`Ph: ${org.phone}`, 36, 54);
    doc.fill(GOLD).font("bold").fontSize(12);
    doc.text(title.toUpperCase(), 36, 30, { width: doc.page.width - 72, align: "right" });
    doc.fill("#000000");
    doc.y = 92;
  }

  private footer(doc: PDFKit.PDFDocument): void {
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      // Zero the bottom margin while writing inside it, or pdfkit adds a page.
      const bottom = doc.page.margins.bottom;
      doc.page.margins.bottom = 0;
      doc.font("body").fontSize(7.5).fill("#828282");
      doc.text("Generated by Saahvik — Hostel Management", 36, doc.page.height - 40, {
        width: doc.page.width - 72,
        align: "center",
        lineBreak: false,
      });
      doc.page.margins.bottom = bottom;
    }
  }

  async receipt(options: {
    org: PdfOrgHeader;
    receiptNo: string;
    paidAt: string;
    rows: [string, string][];
    amountPaisa: number;
    refundedPaisa: number;
  }): Promise<Buffer> {
    return this.render((doc) => {
      this.header(doc, options.org, "Receipt");

      doc.font("bold").fontSize(10).text(options.receiptNo, 36, doc.y);
      doc.font("body").fontSize(9).text(options.paidAt, 36, doc.y - 12, {
        width: doc.page.width - 72,
        align: "right",
      });
      doc.moveDown(0.6);
      doc.moveTo(36, doc.y).lineTo(doc.page.width - 36, doc.y).stroke("#dcdcdc");
      doc.moveDown(0.8);

      doc.fontSize(9);
      for (const [label, value] of options.rows) {
        const y = doc.y;
        doc.fill("#6e6e6e").font("body").text(label, 36, y);
        doc.fill("#000000").text(value, 190, y);
        doc.moveDown(0.5);
      }

      doc.moveDown(0.6);
      const boxY = doc.y;
      doc.rect(36, boxY, doc.page.width - 72, 30).fill("#f8f5ef");
      doc.fill("#000000").font("bold").fontSize(11);
      doc.text("Amount received", 44, boxY + 9);
      doc.text(pdfMoney(options.amountPaisa - options.refundedPaisa), 36, boxY + 9, {
        width: doc.page.width - 80,
        align: "right",
      });
      if (options.refundedPaisa > 0) {
        doc.moveDown(1.6);
        doc.font("body").fontSize(8).fill("#963c3c");
        doc.text(
          `Note: ${pdfMoney(options.refundedPaisa)} of the original ${pdfMoney(options.amountPaisa)} was refunded.`,
          36,
          doc.y,
        );
      }
      this.footer(doc);
    });
  }

  async table(options: {
    org: PdfOrgHeader;
    title: string;
    subtitle?: string;
    columns: PdfTableColumn[];
    rows: string[][];
    summary?: string;
  }): Promise<Buffer> {
    const { org, title, subtitle, columns, rows, summary } = options;
    return this.render((doc) => {
      this.header(doc, org, title);
      doc.font("body").fontSize(8).fill("#6e6e6e");
      doc.text(subtitle ?? `Generated on ${new Date().toLocaleDateString("en-IN")}`, 36, doc.y);
      doc.moveDown(0.8);

      const startX = 36;
      const rowHeight = 18;

      const drawHeaderRow = () => {
        const y = doc.y;
        doc.rect(startX, y, doc.page.width - 72, rowHeight).fill(NAVY);
        doc.fill("#ffffff").font("bold").fontSize(8);
        let x = startX + 5;
        for (const col of columns) {
          doc.text(col.label, x, y + 5, {
            width: col.width - 10,
            align: col.align ?? "left",
            lineBreak: false,
          });
          x += col.width;
        }
        doc.fill("#000000").font("body");
        doc.y = y + rowHeight;
      };

      drawHeaderRow();
      rows.forEach((row, i) => {
        if (doc.y > doc.page.height - 80) {
          doc.addPage();
          doc.y = 40;
          drawHeaderRow();
        }
        const y = doc.y;
        if (i % 2 === 1) {
          doc.rect(startX, y, doc.page.width - 72, rowHeight).fill("#f6f6f4");
          doc.fill("#000000");
        }
        let x = startX + 5;
        doc.fontSize(8);
        row.forEach((cell, c) => {
          doc.text(cell, x, y + 5, {
            width: columns[c].width - 10,
            align: columns[c].align ?? "left",
            lineBreak: false,
            ellipsis: true,
          });
          x += columns[c].width;
        });
        doc.y = y + rowHeight;
      });

      if (summary) {
        doc.moveDown(0.8);
        doc.font("bold").fontSize(9);
        doc.text(summary, startX, doc.y, { width: doc.page.width - 72, align: "right" });
      }
      this.footer(doc);
    });
  }
}
