import { jsPDF } from "jspdf";
import type { Org, Payment } from "@/api/types";
import { formatDateTime, formatDate } from "./format";

/** jsPDF has no ₹ glyph in its built-in fonts, so PDFs use "Rs." */
function pdfMoney(paisa: number): string {
  const rupees = paisa / 100;
  return `Rs. ${rupees.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
}

const NAVY: [number, number, number] = [27, 42, 74];
const GOLD: [number, number, number] = [176, 141, 87];

function header(doc: jsPDF, org: Org | null, title: string): number {
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, 210, 26, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(org?.hostelName ?? "Saahvik Hostel", 14, 11);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(
    [org?.addressLine, org?.city, org?.state, org?.pincode].filter(Boolean).join(", ") || "",
    14,
    17,
  );
  if (org?.phone) doc.text(`Ph: ${org.phone}`, 14, 22);
  doc.setTextColor(...GOLD);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(title.toUpperCase(), 196, 15, { align: "right" });
  doc.setTextColor(0, 0, 0);
  return 34;
}

/** Payment receipt PDF. Returns a blob URL for preview/download. */
export function generateReceiptPdf(payment: Payment, org: Org | null): string {
  const doc = new jsPDF();
  let y = header(doc, org, "Receipt");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(payment.receiptNo, 14, y);
  doc.setFont("helvetica", "normal");
  doc.text(formatDateTime(payment.paidAt), 196, y, { align: "right" });
  y += 8;
  doc.setDrawColor(220, 220, 220);
  doc.line(14, y, 196, y);
  y += 8;

  const rows: [string, string][] = [
    ["Received from", payment.residentName],
    ["Room", payment.roomNumber ?? "-"],
    ["Payment for", payment.type.toUpperCase() + (payment.periodMonth ? ` (${payment.periodMonth})` : "")],
    ["Payment mode", payment.method.replace("_", " ").toUpperCase()],
    ["Recorded by", payment.recordedByName],
  ];
  if (payment.notes) rows.push(["Notes", payment.notes]);

  doc.setFontSize(9);
  for (const [label, value] of rows) {
    doc.setTextColor(110, 110, 110);
    doc.text(label, 14, y);
    doc.setTextColor(0, 0, 0);
    doc.text(String(value), 70, y);
    y += 7;
  }

  y += 4;
  doc.setFillColor(248, 245, 239);
  doc.rect(14, y - 5, 182, 14, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Amount received", 18, y + 3);
  doc.text(pdfMoney(payment.amountPaisa - payment.refundedPaisa), 192, y + 3, { align: "right" });
  if (payment.refundedPaisa > 0) {
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 60, 60);
    doc.text(
      `Note: ${pdfMoney(payment.refundedPaisa)} of the original ${pdfMoney(payment.amountPaisa)} was refunded.`,
      14,
      y,
    );
  }

  doc.setTextColor(130, 130, 130);
  doc.setFontSize(7.5);
  doc.text("Generated by Saahvik - Hostel Management", 105, 285, { align: "center" });

  return doc.output("bloburl").toString();
}

/** Simple tabular report PDF (no autotable dependency). */
export function generateTableReportPdf(options: {
  org: Org | null;
  title: string;
  subtitle?: string;
  columns: { label: string; width: number; align?: "left" | "right" }[];
  rows: string[][];
  summary?: string;
}): string {
  const { org, title, subtitle, columns, rows, summary } = options;
  const doc = new jsPDF();
  let y = header(doc, org, title);

  doc.setFontSize(8);
  doc.setTextColor(110, 110, 110);
  doc.text(subtitle ?? `Generated on ${formatDate(new Date())}`, 14, y);
  y += 7;

  const startX = 14;
  const drawHeaderRow = () => {
    doc.setFillColor(...NAVY);
    doc.rect(startX, y - 4.5, 182, 7, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    let x = startX + 2;
    for (const col of columns) {
      doc.text(col.label, col.align === "right" ? x + col.width - 4 : x, y, {
        align: col.align === "right" ? "right" : "left",
      });
      x += col.width;
    }
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
  };

  drawHeaderRow();
  rows.forEach((row, i) => {
    if (y > 275) {
      doc.addPage();
      y = 20;
      drawHeaderRow();
    }
    if (i % 2 === 1) {
      doc.setFillColor(246, 246, 244);
      doc.rect(startX, y - 4.5, 182, 6.5, "F");
    }
    let x = startX + 2;
    doc.setFontSize(8);
    row.forEach((cell, c) => {
      const col = columns[c];
      const text = doc.splitTextToSize(cell, col.width - 5)[0] ?? "";
      doc.text(text, col.align === "right" ? x + col.width - 4 : x, y, {
        align: col.align === "right" ? "right" : "left",
      });
      x += col.width;
    });
    y += 6.5;
  });

  if (summary) {
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(summary, 196, y, { align: "right" });
  }

  doc.setFont("helvetica", "normal");
  doc.setTextColor(130, 130, 130);
  doc.setFontSize(7.5);
  doc.text("Generated by Saahvik - Hostel Management", 105, 285, { align: "center" });

  return doc.output("bloburl").toString();
}

export { pdfMoney };
